### ISSUE TITLE
Warning:Class 'ProjectImportedOKTest' not found in module 'bootcamp-cordapp-4'

### ISSUE THREAD

**Issue by zhang-shubai** [corda/bootcamp-cordapp#13]
Sorry to bother you....I really encounter trouble.
In the begining, when I want to run ProjectImportedOKTest, the intellJ idea will tell me:
![2019-08-30 20-04-49 的屏幕截图](https://user-images.githubusercontent.com/30946222/64019335-75322e80-cb61-11e9-993a-ccae4edf6dcf.png)

next, I choose 
Use classpath of module:bootcamp-cordapp-4
JRE to be 1.8,
 like the next picture, however, the intellJ idea will still tell me:

Warning:Class 'ProjectImportedOkTest' not found in module 'bootcamp-cordapp-4'
If I choose the other options, the intellJ idea will still warn me, could you tell me how to solve it?
![2019-08-30 20-10-09 的屏幕截图](https://user-images.githubusercontent.com/30946222/64019614-394b9900-cb62-11e9-8bbc-2b1f70ceee13.png)
sorry to bother, not only I'm a beginner of corda, but also one of java.

**Comment by Nastya198** [comment]
@zzz130981 so, how did you solve it?
