### ISSUE TITLE
 ☠   The piece of art was not found in ArtFlowInitiator Project

### ISSUE THREAD

**Issue by prateektiwari7** [corda/bootcamp-cordapp#5]
Hi 

I am facing the issue in calling the Art project code.

` start ArtFlowInitiator title: isha, artist: PartyA, newOwner: PartyB`

 Error says this 

`[ERROR] 15:15:10+0530 [Node thread-1] proxies.ExceptionSerialisingRpcOpsProxy.log - Error during RPC invocation [errorCode=1j2bz3l, moreInformationAt=https://errors.corda.net/OS/4.0/1j2bz3l] {actor_id=internalShell, actor_owning_identity=O=Notary, L=London, C=GB, actor_store_id=NODE_CONFIG, fiber-id=10000001, flow-id=ebeb4248-260d-4af3-9cda-06a579efc8ab, invocation_id=5eede5df-7c2e-44f9-b4d5-b2446cfe01d8, invocation_timestamp=2019-03-27T09:45:09.482Z, origin=internalShell, session_id=99f38c9a-cfee-4f1e-b324-2baafb0c9b63, session_timestamp=2019-03-27T09:42:57.390Z, thread-id=140}
[ERROR] 15:15:10+0530 [Node thread-1] proxies.ExceptionSerialisingRpcOpsProxy.log - Error during RPC invocation [errorCode=1j2bz3l, moreInformationAt=https://errors.corda.net/OS/4.0/1j2bz3l] {actor_id=internalShell, actor_owning_identity=O=Notary, L=London, C=GB, actor_store_id=NODE_CONFIG, fiber-id=10000001, flow-id=ebeb4248-260d-4af3-9cda-06a579efc8ab, invocation_id=5eede5df-7c2e-44f9-b4d5-b2446cfe01d8, invocation_timestamp=2019-03-27T09:45:09.482Z, origin=internalShell, session_id=99f38c9a-cfee-4f1e-b324-2baafb0c9b63, session_timestamp=2019-03-27T09:42:57.390Z, thread-id=140}
[ERROR] 15:15:10+0530 [Node thread-1] proxies.ExceptionSerialisingRpcOpsProxy.log - Error during RPC invocation [errorCode=1j2bz3l, moreInformationAt=https://errors.corda.net/OS/4.0/1j2bz3l] {actor_id=internalShell, actor_owning_identity=O=Notary, L=London, C=GB, actor_store_id=NODE_CONFIG, fiber-id=10000001, flow-id=ebeb4248-260d-4af3-9cda-06a579efc8ab, invocation_id=5eede5df-7c2e-44f9-b4d5-b2446cfe01d8, invocation_timestamp=2019-03-27T09:45:09.482Z, origin=internalShell, session_id=99f38c9a-cfee-4f1e-b324-2baafb0c9b63, session_timestamp=2019-03-27T09:42:57.390Z, thread-id=140}
[ERROR] 15:15:10+0530 [Node thread-1] proxies.ExceptionSerialisingRpcOpsProxy.log - Error during RPC invocation [errorCode=1j2bz3l, moreInformationAt=https://errors.corda.net/OS/4.0/1j2bz3l] {actor_id=internalShell, actor_owning_identity=O=Notary, L=London, C=GB, actor_store_id=NODE_CONFIG, fiber-id=10000001, flow-id=ebeb4248-260d-4af3-9cda-06a579efc8ab, invocation_id=5eede5df-7c2e-44f9-b4d5-b2446cfe01d8, invocation_timestamp=2019-03-27T09:45:09.482Z, origin=internalShell, session_id=99f38c9a-cfee-4f1e-b324-2baafb0c9b63, session_timestamp=2019-03-27T09:42:57.390Z, thread-id=140}
[ERROR] 15:15:10+0530 [Node thread-1] proxies.ExceptionSerialisingRpcOpsProxy.log - Error during RPC invocation [errorCode=1j2bz3l, moreInformationAt=https://errors.corda.net/OS/4.0/1j2bz3l] {actor_id=internalShell, actor_owning_identity=O=Notary, L=London, C=GB, actor_store_id=NODE_CONFIG, fiber-id=10000001, flow-id=ebeb4248-260d-4af3-9cda-06a579efc8ab, invocation_id=5eede5df-7c2e-44f9-b4d5-b2446cfe01d8, invocation_timestamp=2019-03-27T09:45:09.482Z, origin=internalShell, session_id=99f38c9a-cfee-4f1e-b324-2baafb0c9b63, session_timestamp=2019-03-27T09:42:57.390Z, thread-id=140}
[ERROR] 15:15:10+0530 [Node thread-1] proxies.ExceptionSerialisingRpcOpsProxy.log - Error during RPC invocation [errorCode=1j2bz3l, moreInformationAt=https://errors.corda.net/OS/4.0/1j2bz3l] {actor_id=internalShell, actor_owning_identity=O=Notary, L=London, C=GB, actor_store_id=NODE_CONFIG, fiber-id=10000001, flow-id=ebeb4248-260d-4af3-9cda-06a579efc8ab, invocation_id=5eede5df-7c2e-44f9-b4d5-b2446cfe01d8, invocation_timestamp=2019-03-27T09:45:09.482Z, origin=internalShell, session_id=99f38c9a-cfee-4f1e-b324-2baafb0c9b63, session_timestamp=2019-03-27T09:42:57.390Z, thread-id=140}
[ERROR] 15:15:10+0530 [Node thread-1] proxies.ExceptionSerialisingRpcOpsProxy.log - Error during RPC invocation [errorCode=1j2bz3l, moreInformationAt=https://errors.corda.net/OS/4.0/1j2bz3l] {actor_id=internalShell, actor_owning_identity=O=Notary, L=London, C=GB, actor_store_id=NODE_CONFIG, fiber-id=10000001, flow-id=ebeb4248-260d-4af3-9cda-06a579efc8ab, invocation_id=5eede5df-7c2e-44f9-b4d5-b2446cfe01d8, invocation_timestamp=2019-03-27T09:45:09.482Z, origin=internalShell, session_id=99f38c9a-cfee-4f1e-b324-2baafb0c9b63, session_timestamp=2019-03-27T09:42:57.390Z, thread-id=140}

➡️   Starting
🚫   Done
 ☠   The piece of art was not found.
`

Can you please help me with the issue.

**Comment by florian-f** [comment]
Hey, I assume that the creators of these examples intended them to be looked at but not run.
The flow you invoked assumes that an ArtState has been issued in a previous transaction. However there's no flow that you could use to issue such a state. It's probably a good idea to change that :)
