### ISSUE TITLE
Offline Use Is Misleading

### ISSUE THREAD

**Issue by opticyclic** [corda/bootcamp-cordapp#6]
The section in the README "Updating for offline use" is redundant.

Once you have run the project once all your dependencies will be cached locally by gradle anyway.

This section is misleading and redundant and should be removed.

You should also remove the following lines in the build.gradle

https://github.com/corda/bootcamp-cordapp/blob/v4/build.gradle#L16
`flatDir { dirs "lib/dependencies" }`

https://github.com/corda/bootcamp-cordapp/blob/v4/build.gradle#L20
`classpath fileTree(dir: 'lib/dependencies', include: '*.jar')`

https://github.com/corda/bootcamp-cordapp/blob/v4/build.gradle#L35
`flatDir { dirs "${project.rootProject.projectDir}/lib/dependencies" }`

https://github.com/corda/bootcamp-cordapp/blob/v4/build.gradle#L66
`compileClasspath fileTree(dir: 'lib/dependencies', include: '*.jar')`

https://github.com/corda/bootcamp-cordapp/blob/v4/build.gradle#L131-L139
```
task gatherDependencies(type: Copy) {
    into "lib/dependencies"
    from buildscript.configurations.classpath
    from configurations.runtime
    from configurations.compile
    from configurations.testCompile
    from configurations.testRuntime
    from configurations.quasar
}
```

**Comment by florian-f** [comment]
Thanks, removed.
