### ISSUE TITLE
build.gradle Needs Cleaning Up

### ISSUE THREAD

**Issue by opticyclic** [corda/bootcamp-cordapp#7]
Feel free to split this out into lots of smaller issues.

Referring to the v4 branch.

The wrong version of corda is specified:

    corda_release_version = '4.0-SNAPSHOT'
    corda_gradle_plugins_version = '4.0.37'

There are unnecessary repos. 

`mavenLocal()` is only useful for R3 developers using snapshots.

`flatDir { dirs "lib/dependencies" }` is completely unnecessary see https://github.com/corda/bootcamp-cordapp/issues/6 for further details

This whole section should be removed
https://github.com/corda/bootcamp-cordapp/blob/v4/build.gradle#L52-L63
```
sourceSets {
    main {
        resources {
            srcDir "../config/dev"
        }
    }
    test {
        resources {
            srcDir "../config/test"
        }
    }
}
```

In this particular case there is only one module so you don't need it anyway.

In the general case it causes circular dependencies in IDEs and confusion with users as evidenced on Slack.
The only purpose of it is to not duplicate logging config.

https://github.com/corda/bootcamp-cordapp/blob/v4/build.gradle#L83
`deployNodesJava` can just be `deployNodes` like the kotlin project.

https://github.com/corda/bootcamp-cordapp/blob/v4/build.gradle#L84
`directory "./build/nodes"` is the default so doesn't need to be specified.

https://github.com/corda/bootcamp-cordapp/blob/v4/build.gradle#L90
`"$project.group:cordapp:$project.version"` the project name is not `cordapp`

There is no `gradle.properties` specifying the project group, name, version.

There is no need to repeat the `cordapp[]` section in each node when you could do:

        nodeDefaults {
            projectCordapp {
                deploy = true
            }
        }

Why are there no rpc settings for the notary?

**Comment by florian-f** [comment]
Thank you for your feedback, those are good suggestions. I did some cleaning up on the v4 branch recently and addressed some of the points you mentioned here. I'll go and check if I omitted something.

> Why are there no rpc settings for the notary?

In the context of the bootcamp that's not needed, we use the rpc client to look at nodes' vaults and start flows.
